### ISSUE TITLE
Unable to reach /constraint tab

### ISSUE THREAD

**Issue by swapnild2111** [sighupio/gatekeeper-policy-manager#109]
Hello Team,
I have tried all ways your have mentioned in docs & earlier issues, but still getting : 

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Not sure what am missing...
Tried with docker approach, local build & run and k8s approach.

**Comment by ralgozino** [comment]
Hi,

This error is from the browser, right? What do you see on the container's logs?

**Comment by swapnild2111** [comment]
Hello @ralgozino 

Container logs shows:

```
[2021-02-03 11:19:19,411] INFO in app: KUBERNETES_SERVICE_HOST found, assuming to be running inside Kubernetes cluster
[2021-02-03 11:19:19,612] ERROR in app: Exception on /constraints/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 36, in decorated_function
    return f(*args, **kwargs)
  File "./app.py", line 180, in get_constraints
    title="Constraints")
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/constraints.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/app/templates/base.html", line 47, in top-level template code
    {% block content %}{% endblock %}
  File "/app/templates/constraints.html", line 134, in block "content"
    {% for k,v in constraint.spec.parameters.items() %}
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
10.200.1.206 - - [03/Feb/2021:11:19:19 +0000] "GET /constraints/ HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "62.135.241.232"
[pid: 14|app: 0|req: 153/616] 10.200.1.206 () {70 vars in 1723 bytes} [Wed Feb  3 11:19:19 2021] GET /constraints/ => generated 290 bytes in 204 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
```

**Comment by swapnild2111** [comment]
I tried using image tags - v0.4.1 and 0.3rc1

**Comment by ralgozino** [comment]
What gatekeeper version are you running?
Are your constraints working? It seems that one of them has a list as the parameters when we expect a map (dictionary). I'm not sure this is supported by Gatekeeper.

Any chance of sharing with us your constraints definitions so we can try to reproduce the error?

**Comment by swapnild2111** [comment]
Gatekeeper version: `openpolicyagent/gatekeeper:v3.2.2`
Constraints are working perfect, able to see logs + datadog metrics

I have some constraints picked from: https://github.com/open-policy-agent/gatekeeper/tree/master/demo/agilebank
Those are doing basic things and didn't modify much. Couldn't find map reference.

**Comment by swapnild2111** [comment]
ohh, I got your point.

one constraint has: 
```
parameters:
    - cpu
    - memory
```

and other constraints have:
```
parameters:
    tags:
    - latest
```

will correct it and see how it works :)

**Comment by ralgozino** [comment]
great, let us know how it goes :)

**Comment by ralgozino** [comment]
So, it turns out that on the demo files you linked, [there's a constraint that doesn't have a spec defined](https://github.com/open-policy-agent/gatekeeper/blob/master/demo/agilebank/constraints/unique_service_selector.yaml). We weren't handling correctly that case.

I've pushed a fix to handle the absence of the spec field.

Could you please try using the `unstable` docker image tag instead of `v0.4.1`? Let me know if this version works for you.

**Comment by swapnild2111** [comment]
Sure, will do :-)

**Comment by swapnild2111** [comment]
You are Awesome! :)

So when I changed one of the constraint 
From
```
parameters:
      - cpu
      - memory
```
To
```
parameters:
    limits:
      - cpu
      - memory
```
It worked 👍 

Am not sure about the change you introduced in `unstable` version, but the scenario of handling missing spec makes sense.
When I reverted back to v0.4.1, its working fine too.

**Comment by ralgozino** [comment]
Great to hear that! Thanks for the feedback
