### ISSUE TITLE
Internal Server Error on constrainttemplates/

### ISSUE THREAD

**Issue by feguiguren** [sighupio/gatekeeper-policy-manager#2]
I tested this using Kubernetes 1.17 on AWS EKS. 
Logs:
```
[2020-08-05 17:43:10,079] ERROR in app: Exception on /constrainttemplates/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 37, in decorated_function
    return f(*args, **kwargs)
  File "./app.py", line 228, in get_constrainttemplates
    title="Constraint Templates"
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/constrainttemplates.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/app/templates/constrainttemplates.html", line 12, in block "content"
    <div class="ui {% if constrainttemplate.status.created %} green {% endif %} secondary header segment">{{ constrainttemplate.spec.crd.spec.names.kind }} {% if constrainttemplate.status.created %} <span class="ui small horizontal label green">CREATED</span> {% endif %}</div>
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'status'
[pid: 16|app: 0|req: 28094/32412] 127.0.0.1 () {52 vars in 960 bytes} [Wed Aug  5 17:43:10 2020] GET /constrainttemplates/ => generated 290 bytes in 10 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
127.0.0.1 - - [05/Aug/2020:17:43:10 +0000] "GET /constrainttemplates/ HTTP/1.1" 500 290 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
```

The only templates and constraints in the system are Gatekeeper examples:
https://github.com/open-policy-agent/gatekeeper/blob/master/example/templates/k8srequiredlabels_template.yaml
https://github.com/open-policy-agent/gatekeeper/blob/master/example/constraints/all_pod_must_have_gatekeeper_namespaceselector.yaml

**Comment by ralgozino** [comment]
Hi @feguiguren , thanks for reaching out!

Do you get this error every time? I think the issue could be that the constrainttemplates weren't processed yet by Gatekeeper, so they were missing the status field. If you wait some minutes does the problem go away?

Could you also please tell us what version of Gatekeeper are you using?

**Comment by feguiguren** [comment]
Gatekeeper version is gatekeeper:v3.1.0-beta.9
and yes, every time.

**Comment by ralgozino** [comment]
Hola Francisco, 

I think something is broken with your Gatekeeper installation. I can't replicate the issue.
I followed this steps:

Deployed Gatekeeper 3.1.0beta9:

```bash
kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/57e9ccce8002b812065a6a5c31029303037f59a3/deploy/gatekeeper.yaml
```

Deployed the Contrstraint Template

```bash
kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/example/templates/k8srequiredlabels_template.yaml
```

Deployed the Constraint

```bash
kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/example/constraints/all_pod_must_have_gatekeeper_namespaceselector.yaml
```

Deployed GPM

```bash
kustomize build . | kubectl apply -f -
```

The views are working as expected:

![image](https://user-images.githubusercontent.com/6362698/90333011-5b803600-dfc2-11ea-9ea1-eb64a6962937.png)

![image](https://user-images.githubusercontent.com/6362698/90333013-5fac5380-dfc2-11ea-90d7-5cc8c483a1ce.png)

I don't have an EKS cluster to test this right now, but could you please confirm that your Gatekeeper installation is working and that the constraint template and constraint are ok?

Thanks

**Comment by feguiguren** [comment]
Been talking to Gatekeeper folks and they recommended that I upgrade the version to latest, as there may be bugs in gatekeeper:v3.1.0-beta.9. 
WIll upgrade to GA1 and then report back.

Thanks!

**Comment by feguiguren** [comment]
After upgrading to GA1, the error went away. Thanks!

**Comment by ralgozino** [comment]
Thanks for letting us know :)

**Comment by almynamswertakn** [comment]
@ralgozino I just found this thread and was able to resolve the same issue by pulling the `unstable` image.
I am using constraint templates directly from https://github.com/open-policy-agent/gatekeeper-library

Would you please consider releasing a patch with this fix?
I'd like to use your tool , but cannot continue using an "unstable" image in my org.

Thank you!
