### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Harald-koeln** [sighupio/gatekeeper-policy-manager#882]
Hello, in just one cluster (out of ~20) GPM is not starting (Crashloopbackoff) with this log output.
We are using version 0.7.0 and deploy the helm chart with ARGOCD. Kubernetes Version is 1.24.13
Please let me know, if other infos are needed.
Any help appreciated. Thank you!

...
[2023-10-06 07:16:41 +0000] [8] [INFO] In cluster configuration loaded successfully.
[2023-10-06 07:16:41 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 214, in run
    callback(key.fileobj)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 150, in on_client_socket_readable
    self.enqueue_req(conn)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 117, in enqueue_req
    fs = self.tpool.submit(self.handle, conn)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/usr/local/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by ralgozino** [comment]
Hi @Harald-koeln 

This seems indeed strange, let me ask you some questions to better understand the issue:
1. Are the rest of the applications running without issues on the cluster?
2. Are the other clusters that you have running the same version of Kubernetes and GMP?
3. Do you have any resource limits set? can you share the values that you are using to install the chart? please make sure to mask all the sensible info like secrets and URLs
4. Is the node where GPM is running healthy?
5. are there any other security tools or measures running in the cluster that could prevent GPM for creating threads?

Thanks!

**Comment by Harald-koeln** [comment]
Hi @ralgozino ,

thanks for your reply. I will answer your questions, but actually I do not have the need anymore to deploy GPM on that cluster. I've figured out that trivy-operator was additionally deployed on that cluster by another team. We do not need both and maybe this is also the reason for the problems. 
Concerning your questions:
1) yes, gatekeeper (and trivy and other applications) are running without issues
2) yes, there are all the same version
3) no resource limits set by me, only default helm chart values (see below)
4) node is healthy
5) trivy (probably responsible for GPM problems)

`      source:
        chart: gatekeeper-policy-manager
        repoURL: https://sighupio.github.io/gatekeeper-policy-manager
        targetRevision: 0.7.0
        helm:
          releaseName: gatekeeper-policy-manager
          values: |-
            config:
              secretKey: "gatekeeper-policy-manager"
            ingress:
              enabled: true
              hosts:
                - host: "gpm.{{ metadata.annotations.cluster_wildcard_domain }}"
                  paths:
                    - "/"`

**Comment by ralgozino** [comment]
I'm glad you sorted it out, I'll probably do some tests with `trivy-operator` (I haven't heard of it before) anyway to see if there's something we can do to make them compatible.

thanks!

**Comment by ralgozino** [comment]
hey @Harald-koeln 

I tried reproducing the error with some load testing but I can't trigger it.

Do you have some limit sets on the number of processes that a container can run? or are the used inodes in the node close to the limit maybe?

Anything particular of your setup that we should know to replicate the issue?

I wonder if the same/similar issue happens to you with the new Go backend that is in development, would you mind testing it? You just need to change the image tag to `go`, i.e. `v1.0.7` -> `go`. Please let me know if it happens there also. Notice that the go backend does not support OIDC auth yet in case you are using it.

**Comment by Harald-koeln** [comment]
Hi @ralgozino , thank you very much. The go-Version is working on all 5 clusters where I observed problems with the python version.
As far as I know there are no special limits about the number of processes or inodes.
We do not use OIDC here so using the go-version is fine for us. Thanks!

**Comment by ralgozino** [comment]
glad to hear that! any feedback on the go backend version is very welcomed :-)

**Comment by ralgozino** [comment]
closing this issue, the Go backend is now the default and will be the official version in the next release.
